### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cevich**
Add monitoring for CRI-O in an attempt to replace travis

### CODE REVIEW

**Comment by cevich** [comment]
quick question too:  if I use multiple documents as in the example, are the results/output separated by "context" or just lumped all into one ourput file?

**Comment by jlebon** [comment]
bot, add author to whitelist

**Comment by jlebon** [comment]
Each new testsuite (separated by `---`) will yield a different context, with different outputs. Check out PRs in e.g. ostree & rpm-ostree for example.

**Comment by cevich** [comment]
Excellent.

**Comment by cevich** [comment]
@jlebon FWIW, #57 isn't a blocker for this.  The crio-o guys want to test on Fedora with this, and can limp along on travis for Ubuntu.  Though having a unified PI-tester would be nice for re-usability.  I don't think it's a hard-requirement.

**Comment by jlebon** [comment]
@cevich Sounds good. Just let me know when the proper access has been secured and we can move forward.

**Comment by cevich** [comment]
oh right, thx for reminding me.  mrunal said he's still working on it.

**Pull request closed without merging**
