### PR TITLE
papr: hook papr to papr

### PR DESCRIPTION
**Pull request by jlebon**
So that we have more PAPR in our PAPR.

This is just running flake8 for now, because I want to hook up homu to
this repo.

This is a start for https://github.com/projectatomic/papr/issues/43.

### CODE REVIEW

**Comment by cgwalters** [comment]
LGTM - until then, `Squash and merge`?

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
Yay! \o/

**Pull request merged**
