### PR TITLE
Split out distro list into its own doc and add fedora/26/atomic/nightly

### PR DESCRIPTION
**Pull request by jlebon**
See commits comments.

### CODE REVIEW

**Comment by cgwalters** [comment]
The term "nightly" upsets me :smile:   At least now Fedora releng sometimes does things twice a day.

How about we just match the Fedora releng terms, i.e. it's `fedora/branched/26/atomic`?

**Comment by jlebon** [comment]
Ahh interesting. It does indeed appear to sometimes be composed more than once a day (looking at https://kojipkgs.fedoraproject.org/compose/branched/).

> How about we just match the Fedora releng terms, i.e. it's `fedora/branched/26/atomic`?

Hmm, this might be bikeshed, though I think I'd really prefer to keep the `fedora/$releasever/atomic` prefix at least, for consistency. Maybe a different suffix than `nightly` then? I initially used `nightly` since that how it's called e.g. at https://www.happyassassin.net/nightlies.html. For example, we can also have (and I'd like to have) a `fedora/25/atomic/nightly`!

Or we could also just name it `fedora/26/atomic`, which will become the supported name once it's released.

**Comment by cgwalters** [comment]
For ostree refs at least the convention is to have "qualifiers" in the middle, and the end part describes the system.  Admittedly I made that up...but it does predate PAPR and looks similar.  We might actually ask the question whether the PAPR name needs to be distinct from the ostree ref; if your look at it as a "selector", perhaps one could drop "x86_64" and have it be the default.

**Comment by cgwalters** [comment]
IOW, it's `fedora/25/atomic-host` (AKA current PAPR `fedora/25/atomic`, or current ostree `fedora/25/x86_64/docker-host`)

**Comment by jlebon** [comment]
I think I'd be OK with renaming the atomic ones to `atomic-host` to better align with their ostree refs. (Not to mention the official name of the variant is Atomic Host anyway!).

> We might actually ask the question whether the PAPR name needs to be distinct from the ostree ref

Though note that we also support the cloud images. Another issues is that we could have multiple streams that all have the same ostree ref (but at different stages of promotion). IIRC, that's the case currently for the twoweek composes until one is chosen for release, right?

So then, it seems more important for the names to not denote the ostree ref, but the origin of the stream itself, e.g. official vs non-official, released vs. testing, etc...

**Comment by jlebon** [comment]
I opened https://github.com/projectatomic/papr/issues/46 to track the renaming to `atomic-host` and added a fixup here to just name it `fedora/26/atomic` for now.

**Comment by jlebon** [comment]
> Another issues is that we could have multiple streams that all have the same ostree ref (but at different stages of promotion).

I mean, ideally, this would be done solely through ostree branches and promotions. But AIUI that's not how it works right now.

**Comment by jlebon** [comment]
> I opened #46 to track the renaming to `atomic-host` and added a fixup here to just name it `fedora/26/atomic` for now.

@cgwalters Does this work for now?

**Comment by cgwalters** [comment]
Sure.

**Pull request merged**
