### PR TITLE
Addition of conmon under papr

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by jlebon** [comment]
Can you confirm that `rh-atomic-bot` has write access to the repo?

**Comment by jlebon** [comment]
Did you also want Homu set up for this repo?

**Comment by baude** [comment]
yes please

**Comment by jlebon** [comment]
OK, this is done! If you want faster reaction times to new PRs/comments/etc..., you might want anyone with admin rights to head over to https://apps.fedoraproject.org/github2fedmsg and turn on notifications for the repo.

**Pull request merged**
